CREATE DATABASE pokemonDB;

USE pokemonDB;

CREATE TABLE Users (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(255) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL
);

CREATE TABLE Generation (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE Region (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    GenerationId INT,
    FOREIGN KEY (GenerationId) REFERENCES Generation(Id) ON DELETE SET NULL
);

CREATE TABLE Type (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE Pokemon (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    TypeOneId INT NOT NULL,
    TypeTwoId INT NULL,
    GenerationId INT NOT NULL,
    FOREIGN KEY (TypeOneId) REFERENCES Type(Id) ON DELETE CASCADE,
    FOREIGN KEY (TypeTwoId) REFERENCES Type(Id) ON DELETE SET NULL,
    FOREIGN KEY (GenerationId) REFERENCES Generation(Id) ON DELETE CASCADE
);

CREATE TABLE TypeInteraction (
    StrongType INT NOT NULL,
    WeakType INT NOT NULL,
    PRIMARY KEY (StrongType, WeakType),
    FOREIGN KEY (StrongType) REFERENCES Type(Id) ON DELETE CASCADE,
    FOREIGN KEY (WeakType) REFERENCES Type(Id) ON DELETE CASCADE
);

CREATE TABLE Collection (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    PokemonId INT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY (PokemonId) REFERENCES Pokemon(Id) ON DELETE CASCADE
);